/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Grafico.NaveGrafico;
import Grafico.Panel;
import Grafico.RectanguloGrafico;
import Grafico.Ventana;
import Logica2.Coordenada;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Clint
 */
public class Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
        Ventana nuestraventana = new Ventana("juego");
           
            /**
           * se crea lista y dimenciones que tendra el juego
           */
           ArrayList ArregloDeobjetos = new ArrayList();
           
         
          //coordenadas derectangulo ensayo
          Coordenada cor1 = new Coordenada(250,250);
          // coordenada circulo
           Coordenada cor2 = new Coordenada(350,350);
          //nave
        Coordenada cor3 = new Coordenada(475,500);//punta
        Coordenada cor4 = new Coordenada(425,575);//izquierda
        Coordenada cor5 = new Coordenada(525,575);//derecha
        
        NaveGrafico nave = new NaveGrafico(cor3,cor4,cor5,Color.YELLOW);
        
       Coordenada Salida = new Coordenada(0,0);//se crean balas hacia abajp  rango  eje x
       RectanguloGrafico Asteriode = new RectanguloGrafico(Salida,25,25,Color.BLUE);
          ArregloDeobjetos.add(nave);
          
       
       Coordenada Salida1 = new Coordenada(0,0);//se crean balas hacia abajp  rango  eje x
       RectanguloGrafico Asteriode1 = new RectanguloGrafico(Salida1,25,25,Color.BLUE);
          ArregloDeobjetos.add(nave);
     
       Coordenada Salida2 = new Coordenada(0,0);//se crean balas hacia abajp  rango  eje x
       RectanguloGrafico Asteriode2 = new RectanguloGrafico(Salida2,25,25,Color.BLUE);
          ArregloDeobjetos.add(nave);
          
       
       Coordenada Salida3 = new Coordenada(0,0);//se crean balas hacia abajp  rango  eje x
       RectanguloGrafico Asteriode3 = new RectanguloGrafico(Salida3,25,25,Color.BLUE);
          ArregloDeobjetos.add(nave);
          
       
       Coordenada Salida4 = new Coordenada(0,0);//se crean balas hacia abajp  rango  eje x
       RectanguloGrafico Asteriode4 = new RectanguloGrafico(Salida4,25,25,Color.BLUE);
       
        ArregloDeobjetos.add(Asteriode);
       ArregloDeobjetos.add(Asteriode1);
       ArregloDeobjetos.add(Asteriode2);
       ArregloDeobjetos.add(Asteriode3);
       ArregloDeobjetos.add(Asteriode4);
        
        ArregloDeobjetos.add(nave);
        
           
            Panel nuestroPanel = new Panel(ArregloDeobjetos);
            nuestroPanel.refAst(Asteriode, Asteriode1, Asteriode2, Asteriode3, Asteriode4);
            nuestroPanel.refNave(nave);
                nuestraventana.add(nuestroPanel);
                nuestraventana.setSize(800,600);
                nuestraventana.setBackground(Color.darkGray);
                nuestraventana.setVisible(true);
                nuestroPanel.run
        ();
    }
    
    public void inicio(){
           
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
