/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import Logica.disparo;
import Logica.posicion;
import javax.swing.JOptionPane;

/**
 * Metodo principal JFrame que contiene la parte grafica y parte logica de KeyPressed para el movimiento del cubo y ejecucion de hilos
 * @author Juan David Reyes. 
 * @author Juan Ricardo Rodriguez Campos.
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        
        
       
        
        /*
        posicion p = new posicion(bala,bala.getX(),bala.getY(),cubo);
        p.datos();
        p.start();
        */
        
        
        // TODO add your handling code here:
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cubo = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        cañon1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        cubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/img/naved.jpg"))); // NOI18N
        cubo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cuboFocusGained(evt);
            }
        });
        cubo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cuboKeyPressed(evt);
            }
        });

        dis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/img/disparoN.jpg"))); // NOI18N

        cañon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego/img/nave.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(cañon1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cubo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cañon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cubo)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuboKeyPressed
        // TODO add your handling code here:
       
      
        
    }//GEN-LAST:event_cuboKeyPressed

    private void cuboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cuboFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cuboFocusGained
/**
 * KeyPressed para la ejeccion de codigo con los botones.
 * @param evt 
 */
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        // TODO add your handling code here:
         /*int tecla2 = evt.getKeyCode();
         char tecla = evt.getKeyChar();
         System.out.println(tecla2);
        */
         
        int x = cubo.getX();
         int y = cubo.getY();
        
        //System.out.println(x+y);
        //System.out.println(evt.getKeyChar());
        if(evt.getKeyCode()==39){
            
            x=x+3;
            
            
            if(x >=700){
                x=700;
                //cubo.setLocation(x, y);
            }
            cubo.setLocation(x, y);
        }
        if(evt.getKeyCode()==37){
            x=x-4;
            //cubo.setLocation(x, y);
            if(x<=5){
                x=5;
                //cubo.setLocation(x, y);
            }
            cubo.setLocation(x, y);
        }
        
        if(evt.getKeyCode()==38){
        disparo d = new disparo(cubo,dis);
        d.start();
        }
        
        
        posicion p1 = new posicion(cañon1,cubo,dis);
        p1.datos();
        p1.start();
        
        
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cañon1;
    private javax.swing.JLabel cubo;
    private javax.swing.JLabel dis;
    // End of variables declaration//GEN-END:variables
}
